c001:
  healthchecks:
    - name: Check scratch is mounted
      command: "df"
      ok_exitcode: 0
      timeout: 5
    - name: Check no errors on ib device
      command: "cat /etc/os-release"
      ok_exitcode: 0
c002:
  healthchecks:
    - name: Check scratch is mounted
      command: "df | grep scratch"
      ok_exitcode: 0
    - name: Check no errors on ib device
      command: "ibstatus | grep errors"
      ok_exitcode: 0


